stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."

test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying to GitHub..."
    - git config --global user.email "vakvaer@stud.ntnu.no"
    - git config --global user.name "Vilde Adela Svejkovsky Kværne"
    - git remote add github https://vildesk:${GITHUB_TOKEN}@github.com/vildesk/Hopla.git
    - git push github HEAD:main
